version: '3.7'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dados:/var/lib/postgresql/data
  web:
    image: node:latest
    container_name: web
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/knexapp
    working_dir: /usr/knexapp
    command: bash -c "yarn --no-bin-links && yarn start"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"